name: Hello Python
on:
    workflow_dispatch:

jobs:
  hello_python:
    name: Hello Python
    runs-on: arch

    steps:
      - name: setup Python
        uses: ganadist/setup-python@v0.0.2
        with:
          python-version: 3.9.16

