name: Hello Python
on:
    workflow_dispatch:

jobs:
  hello_python:
    name: Hello Python
    runs-on: arch

    steps:
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15

