name: Hello Python
on:
    workflow_dispatch:

jobs:
  hello_python:
    name: Hello Python
    runs-on: arch

    steps:
      - name: Show OS
        run: cat /etc/os-release
      - name: Setup Python
        uses: ganadist/setup-python@v0.0.9
        with:
          python-version: 3.9.16
          versions-manifest-repo-owner: ganadist
          versions-manifest-repo-name: setup-python
          versions-manifest-repo-branch: support-non-ubuntu-test

